"""empty message

Revision ID: 35f5e737bf12
Revises: 62247ee6885f
Create Date: 2020-08-23 04:38:34.802512

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '35f5e737bf12'
down_revision = '62247ee6885f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('projectLink', sa.String(length=128), nullable=True))
    op.create_unique_constraint(None, 'projects', ['projectLink'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'projects', type_='unique')
    op.drop_column('projects', 'projectLink')
    # ### end Alembic commands ###
