"""New fields in user Model

Revision ID: 46a5ee9d7779
Revises: 5dc40064dcaa
Create Date: 2020-08-02 03:19:08.076450

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '46a5ee9d7779'
down_revision = '5dc40064dcaa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('person', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'person', 'user', ['user_id'], ['id'])
    op.add_column('user', sa.Column('about_me', sa.String(length=140), nullable=True))
    op.add_column('user', sa.Column('last_seen', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'last_seen')
    op.drop_column('user', 'about_me')
    op.drop_constraint(None, 'person', type_='foreignkey')
    op.drop_column('person', 'user_id')
    # ### end Alembic commands ###
