"""empty message

Revision ID: 62247ee6885f
Revises: c8ae2055a022
Create Date: 2020-08-23 04:28:25.719417

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '62247ee6885f'
down_revision = 'c8ae2055a022'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('projects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_projects_timestamp'), 'projects', ['timestamp'], unique=False)
    op.create_table('user_projects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_projects')
    op.drop_index(op.f('ix_projects_timestamp'), table_name='projects')
    op.drop_table('projects')
    # ### end Alembic commands ###
