"""empty message

Revision ID: cc7e1ff0360a
Revises: 8e1946a2db65
Create Date: 2020-08-23 04:13:07.368722

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cc7e1ff0360a'
down_revision = '8e1946a2db65'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_projects_timestamp', table_name='projects')
    op.drop_column('projects', 'timestamp')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('timestamp', sa.DATETIME(), nullable=True))
    op.create_index('ix_projects_timestamp', 'projects', ['timestamp'], unique=False)
    # ### end Alembic commands ###
